{
  "hash": "0f9db907f35c61982cda9f112370652a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Leo Leung\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\n**In this analysis, I look at the median age across counties in Florida, and\nask which communities we measure most and least reliably.**\n\n---\n\n## Choosing what to measure\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"FL\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B01002_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                     variable   estimate   moe\n  <chr> <chr>                    <chr>         <dbl> <dbl>\n1 12001 Alachua County, Florida  B01002_001     32.2   0.2\n2 12003 Baker County, Florida    B01002_001     38.1   0.7\n3 12005 Bay County, Florida      B01002_001     41.4   0.3\n4 12007 Bradford County, Florida B01002_001     40.5   1.2\n5 12009 Brevard County, Florida  B01002_001     46.8   0.2\n6 12011 Broward County, Florida  B01002_001     41.3   0.2\n```\n\n\n:::\n:::\n\n\n\n**[How many rows did you get? Does that match the number of counties in your state?]**\nThere are 67 counties in Florida and my row count matches.\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                      estimate   moe moe_pct\n   <chr>                        <dbl> <dbl>   <dbl>\n 1 Lafayette County, Florida     41.8   2.6    6.22\n 2 Liberty County, Florida       39.1   2.1    5.37\n 3 Glades County, Florida        45.8   1.9    4.15\n 4 Gulf County, Florida          47.3   1.5    3.17\n 5 Bradford County, Florida      40.5   1.2    2.96\n 6 Holmes County, Florida        42.4   1.2    2.83\n 7 Jefferson County, Florida     47     1.3    2.77\n 8 Calhoun County, Florida       41.8   0.9    2.15\n 9 Hamilton County, Florida      40.6   0.8    1.97\n10 Gilchrist County, Florida     42.7   0.8    1.87\n```\n\n\n:::\n:::\n\n\n\n**[Which county has the largest margin of error relative to its estimate? How large\nis it?]**\nLafayette County, Florida has the largest margin of error relative to its estimate, which is around 6.22%.\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 2  ~ \"High confidence\",\n    moe_pct < 5 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    59\n2 Low confidence      2\n3 Moderate            6\n```\n\n\n:::\n:::\n\n\n\n**[How many counties fall into each category?]**\nIf the cutoff is 5% and 10%, then 65 of them will land to high confidence and only 2 county will land to moderate. That is why I manually change the cutoffs to 2% and 5%, which showcase 59 in high confidence, 6 in moderate and 2 in low confidence. \n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                     myvarE myvarM    popE  popM\n  <chr> <chr>                     <dbl>  <dbl>   <dbl> <dbl>\n1 12001 Alachua County, Florida    32.2    0.2  281751    NA\n2 12003 Baker County, Florida      38.1    0.7   28186    NA\n3 12005 Bay County, Florida        41.4    0.3  181368    NA\n4 12007 Bradford County, Florida   40.5    1.2   27888    NA\n5 12009 Brevard County, Florida    46.8    0.2  620533    NA\n6 12011 Broward County, Florida    41.3    0.2 1946127    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 2  ~ \"High confidence\",\n    moe_pct < 5 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         59        369666.\n2 Low confidence           2          7842.\n3 Moderate                 6         17153.\n```\n\n\n:::\n:::\n\n\n\n**[What is the average population of high-confidence counties versus low-confidence\ncounties? Is there a pattern?]**\n\nThe avaerage population of high-confidence counties is 337126 in 65 counties, while the average population of low-confidence is 7842 in 2 counties. It means that larger population sizes have higher data confidence. \n---\n\n## What this means for policy\n\n\n**[Your 200–250 word reflection goes here.]**\n\n1. In Florida, the communities we know the least about are small, rural counties such as Lafayette County and Liberty County. In our analysis, Lafayette County had the highest relative margin of error at 6.22%, while Liberty County, Florida have the margin of error at 5.37%. This two counties also fell into the moderate confidence category, with an average population of just 7,842.\n\n2. This uncertainty stems directly from how the American Community Survey (ACS) operates. Because the ACS collects data from a sample of households rather than conducting a full census count, smaller populations naturally yield smaller sample sizes. With fewer completed responses, individual sample variations will lead to higher random variations on a bigger impact, driving up the margin of error percentage relative to the estimate.\n\n3. If a state agency allocated funding based on median ages, like distributing senior services grants.  Treating every county's estimate as equally certain means that the rural residents would suffer most. In small counties, less sample calculated median age. If Lafayette County's median age were underestimated due to sampling error and there is more outliner, state algorithms might misclassify it as a younger community and withhold essential funding for senior centers, elder healthcare, and specialized transit. Meanwhile, large urban counties like Miami-Dade have massive sample sizes, negligible relative error, and stable funding streams. Relying uncritically on ACS estimates without accounting for margin of error disproportionately harms vulnerable, small-town communities by compounding statistical uncertainty with financial deprivation.\n---\n\n## Optional challenges - For those craving more\n\n\n---\n\n## Before you submit\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}